"""infrastructure and oplog

Revision ID: 0e37569cf689
Revises: 10bd1c9e1fe5
Create Date: 2026-05-19 14:43:52.291764
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0e37569cf689'
down_revision: str | None = '10bd1c9e1fe5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_engagement_id'), 'infrastructure', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_name'), 'infrastructure', ['name'], unique=False)
    op.create_table('oplog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('dest_host', sa.String(length=255), nullable=True),
    sa.Column('tool', sa.String(length=120), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('mitre_technique', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oplog_engagement_id'), 'oplog', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_oplog_ts'), 'oplog', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oplog_ts'), table_name='oplog')
    op.drop_index(op.f('ix_oplog_engagement_id'), table_name='oplog')
    op.drop_table('oplog')
    op.drop_index(op.f('ix_infrastructure_name'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_engagement_id'), table_name='infrastructure')
    op.drop_table('infrastructure')
    # ### end Alembic commands ###
