"""ghostwriter finding fields

Revision ID: 43062f66bdc0
Revises: 79e70ed75087
Create Date: 2026-05-19 14:12:07.879545
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '43062f66bdc0'
down_revision: str | None = '79e70ed75087'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding_templates', sa.Column('finding_type', sa.String(length=60), nullable=True))
    op.add_column('finding_templates', sa.Column('host_detection_md', sa.Text(), nullable=True))
    op.add_column('finding_templates', sa.Column('network_detection_md', sa.Text(), nullable=True))
    op.add_column('finding_templates', sa.Column('finding_guidance_md', sa.Text(), nullable=True))
    op.add_column('finding_templates', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('findings', sa.Column('finding_type', sa.String(length=60), nullable=True))
    op.add_column('findings', sa.Column('host_detection_md', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('network_detection_md', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('tags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'tags')
    op.drop_column('findings', 'network_detection_md')
    op.drop_column('findings', 'host_detection_md')
    op.drop_column('findings', 'finding_type')
    op.drop_column('finding_templates', 'tags')
    op.drop_column('finding_templates', 'finding_guidance_md')
    op.drop_column('finding_templates', 'network_detection_md')
    op.drop_column('finding_templates', 'host_detection_md')
    op.drop_column('finding_templates', 'finding_type')
    # ### end Alembic commands ###
