"""access paths and steps

Revision ID: 7bcafc656c10
Revises: b87f93039c1c
Create Date: 2026-05-19 13:09:37.077682
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7bcafc656c10'
down_revision: str | None = 'b87f93039c1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_paths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('target_asset_id', sa.Uuid(), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_paths_engagement_id'), 'access_paths', ['engagement_id'], unique=False)
    op.create_table('access_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('command_or_action', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('from_asset_id', sa.Uuid(), nullable=True),
    sa.Column('to_asset_id', sa.Uuid(), nullable=True),
    sa.Column('compromised_user_id', sa.Uuid(), nullable=True),
    sa.Column('mitre_technique', sa.String(length=16), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['compromised_user_id'], ['compromised_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['path_id'], ['access_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_steps_path_id'), 'access_steps', ['path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_steps_path_id'), table_name='access_steps')
    op.drop_table('access_steps')
    op.drop_index(op.f('ix_access_paths_engagement_id'), table_name='access_paths')
    op.drop_table('access_paths')
    # ### end Alembic commands ###
