"""compromised users and artifacts

Revision ID: 7de26335dca0
Revises: f9635aab8dc3
Create Date: 2026-05-19 13:02:04.851802
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7de26335dca0'
down_revision: str | None = 'f9635aab8dc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('introduced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('introduced_by', sa.Uuid(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['introduced_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_asset_id'), 'artifacts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_artifacts_engagement_id'), 'artifacts', ['engagement_id'], unique=False)
    op.create_table('compromised_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('workstream_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.String(length=160), nullable=True),
    sa.Column('privilege', sa.String(length=16), nullable=False),
    sa.Column('method_md', sa.Text(), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compromised_users_asset_id'), 'compromised_users', ['asset_id'], unique=False)
    op.create_index(op.f('ix_compromised_users_engagement_id'), 'compromised_users', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_compromised_users_username'), 'compromised_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compromised_users_username'), table_name='compromised_users')
    op.drop_index(op.f('ix_compromised_users_engagement_id'), table_name='compromised_users')
    op.drop_index(op.f('ix_compromised_users_asset_id'), table_name='compromised_users')
    op.drop_table('compromised_users')
    op.drop_index(op.f('ix_artifacts_engagement_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_asset_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
