"""domains and webapps

Revision ID: a3f2af11fda0
Revises: 43062f66bdc0
Create Date: 2026-05-19 14:32:11.206649
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a3f2af11fda0'
down_revision: str | None = '43062f66bdc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('workstream_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_subdomain', sa.Boolean(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_engagement_id'), 'domains', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=False)
    op.create_index(op.f('ix_domains_workstream_id'), 'domains', ['workstream_id'], unique=False)
    op.create_table('webapps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('workstream_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('host_asset_id', sa.Uuid(), nullable=True),
    sa.Column('domain_id', sa.Uuid(), nullable=True),
    sa.Column('tech_md', sa.Text(), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webapps_engagement_id'), 'webapps', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_webapps_host_asset_id'), 'webapps', ['host_asset_id'], unique=False)
    op.create_index(op.f('ix_webapps_workstream_id'), 'webapps', ['workstream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webapps_workstream_id'), table_name='webapps')
    op.drop_index(op.f('ix_webapps_host_asset_id'), table_name='webapps')
    op.drop_index(op.f('ix_webapps_engagement_id'), table_name='webapps')
    op.drop_table('webapps')
    op.drop_index(op.f('ix_domains_workstream_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_engagement_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
