"""evidence

Revision ID: b87f93039c1c
Revises: 7de26335dca0
Create Date: 2026-05-19 13:06:11.027793
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b87f93039c1c'
down_revision: str | None = '7de26335dca0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('parent_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_engagement_id'), 'evidence', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_evidence_parent_id'), 'evidence', ['parent_id'], unique=False)
    op.create_index(op.f('ix_evidence_parent_type'), 'evidence', ['parent_type'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_parent_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_parent_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_engagement_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
