"""findings and templates

Revision ID: f55019d3554d
Revises: 7bcafc656c10
Create Date: 2026-05-19 13:13:21.816664
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f55019d3554d'
down_revision: str | None = '7bcafc656c10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('severity_default', sa.String(length=16), nullable=False),
    sa.Column('cwe', sa.String(length=16), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('impact_md', sa.Text(), nullable=True),
    sa.Column('remediation_md', sa.Text(), nullable=True),
    sa.Column('references_md', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('workstream_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cvss_vector', sa.String(length=120), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe', sa.String(length=16), nullable=True),
    sa.Column('cve', sa.String(length=24), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('impact_md', sa.Text(), nullable=True),
    sa.Column('reproduction_md', sa.Text(), nullable=True),
    sa.Column('remediation_md', sa.Text(), nullable=True),
    sa.Column('references_md', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['finding_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_engagement_id'), 'findings', ['engagement_id'], unique=False)
    op.create_table('finding_assets',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_assets')
    op.drop_index(op.f('ix_findings_engagement_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('finding_templates')
    # ### end Alembic commands ###
