"""assets and activity log

Revision ID: f9635aab8dc3
Revises: d64b359b8cbe
Create Date: 2026-05-19 12:57:43.141290
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f9635aab8dc3'
down_revision: str | None = 'd64b359b8cbe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('workstream_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=120), nullable=True),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('owner_op', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_op'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_engagement_id'), 'assets', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_assets_identifier'), 'assets', ['identifier'], unique=False)
    op.create_index(op.f('ix_assets_workstream_id'), 'assets', ['workstream_id'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('target_asset_id', sa.Uuid(), nullable=True),
    sa.Column('workstream_id', sa.Uuid(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('mitre_technique', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_engagement_id'), 'activity_log', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_activity_log_target_asset_id'), 'activity_log', ['target_asset_id'], unique=False)
    op.create_index(op.f('ix_activity_log_ts'), 'activity_log', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_log_ts'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_target_asset_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_engagement_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_assets_workstream_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_identifier'), table_name='assets')
    op.drop_index(op.f('ix_assets_engagement_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
